---
driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local
      attrs_outputs:
        servers_sofia: private_ips

platforms:
  - name: terraform

suites:
  - name: default
